Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/jammy64"
	config.vm.network "forwarded_port", guest: 80, host: 8080
	config.vm.network "public_network", ip: "192.168.2.10", bridge: "Intel(R) Wi-Fi 6 AX201 160MHz"
	config.vm.synced_folder ".", "/vagrant"
	
	config.vm.provider :virtualbox do |vb|
		vb.cpus = 2
		vb.memory = "4096"
		vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
	end
end